### PR TITLE
Add option to send bytes over USB to trigger a reboot + scripts

### PR DESCRIPTION
**Pull request by datdenkikniet**
Now, sending `0xDABAD000` (in big endian order) over the USB serial triggers a restart into the USB bootloader with a specific feature enabled.

Pin `defmt` version to v0.3.2 for now to avoid the wire-breaking change.

Add some scripts that help with automagically restarting the probe, running `elf2uf2-rs` and starting `defmt-print` on the relevant serial port :D 

This makes debugging/programming without a debugger to attach to the probe even more seamless

TODO:
- [x] Feature gate USB restart
- [x] Discuss: should the USB restart feature be enabled by default? IMO: no, too "hacky"/"debuggy" for everyday use. Explicitly opting in with a feature feels more logical

### CODE REVIEW

**Comment by Yatekii** [comment]
I like this feature, but can we make it something else than `0xDEADBEEF`? While I myself take no offense and would choose a value like that I have seen people make a fuss about it in the past.

**Comment by datdenkikniet** [comment]
Huh, absolutely! I wasn't aware that it was a "controversial" magic number, but will keep that in mind for the future now.

**Comment by Yatekii** [comment]
Yeah, I have trouble tracking controversial values myself as it feels many things are controversial nowadays ... Thanks for changing it =)

**Comment by Yatekii** [comment]
Also, the code looks nice, great work, I love this feature!

Do you think it would be possible to make the script a cargo xtask (or similar)? While I despise windows, I heard quite some folks use it and I am generally trying to be aware of portability :)

**Comment by datdenkikniet** [comment]
I will try! Yeah, the scripts are (for the most part) a quick and dirty solution. It would be nice if they're a bit more portable.

**Comment by datdenkikniet** [comment]
Done! I have no idea if this is how you usually set up xtasks. I guess we should follow the `xtask` people's advice and set up the workspace properly? Now it's a bit of a mess when it comes to setting up the correct compilation target...

**Comment by datdenkikniet** [comment]
This also takes me back to the 2nd point on the TODO list: if we have this whole tool that only really works if we've got the `defmt-bbq` and `usb-serial-reboot` features enabled, should they be on by default?

**Comment by Yatekii** [comment]
This is awesome!

I am not sure how realistic it is that UART accidentally triggers the magic byte? Maybe it's a bit risky?

**Comment by datdenkikniet** [comment]
Honestly, I have no idea. But, just adding an alias in `.cargo/config` that builds with the correct features and then delegates to xtask is probably better, now that I think of it xd.

**Comment by Yatekii** [comment]
Yeah workspaces in general are a bit annoying to manage imo ... mixed targets is even worse ...

But an alias with correct features would be very nice =)

**Comment by datdenkikniet** [comment]
There, updated the README and `.cargo/config.toml` for some ease-of-use

**Review by Yatekii — APPROVED** [review]
Splendid work, thank you =)

**Pull request merged**
